mybatis:
  type-aliases-package: com.dnk.swa.dto
  mapperLocations: classpath:mapping/*.xml
server:
  port: 8880
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /stt/resources/**
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://98.28.5.80:3306/STT?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: stt
    password: stt##123
#  datasource2:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://98.28.8.45:64435/recsee3p
#    username: stt
#    password: stt
  servlet:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB