mybatis:
  type-aliases-package: com.dnk.swa.dto
  mapperLocations: classpath:mapping/*.xml
server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://98.28.5.80:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: itray##123
  servlet:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB